"""Add 'description' and 'priority' fields to ToDo model

Revision ID: 68f8bd6eb0b3
Revises: 4a1df9b42515
Create Date: 2024-08-04 13:06:28.035123

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '68f8bd6eb0b3'
down_revision = '4a1df9b42515'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('to_do', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('priority', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('to_do', schema=None) as batch_op:
        batch_op.drop_column('priority')
        batch_op.drop_column('description')

    # ### end Alembic commands ###
